source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'KFRFuzzyDateTranslator_Tests', :exclusive => true do
  pod "KFRFuzzyDateTranslator", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
